language: python
python:
  - "3.6"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y graphviz
install:
  - pip install -r requirements.txt
script:
  - coverage run --source p3 setup.py test
after_success:
  - codecov -t ${CODECOV_TOKEN}
